# Generated by Django 5.1.4 on 2025-01-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workinghours",
            name="day_of_week",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ]
            ),
        ),
    ]
