# Generated by Django 5.1.4 on 2025-01-12 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_alter_workinghours_day_of_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentrequest",
            name="id_request",
        ),
    ]
