# Generated by Django 5.1.4 on 2025-01-13 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0003_remove_appointmentrequest_id_request"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="inquiry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.inquiry",
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="inquiry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customers.inquiry",
            ),
        ),
    ]
