# Generated by Django 5.1.4 on 2025-01-15 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0004_appointment_inquiry_appointmentrequest_inquiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="client",
        ),
    ]
