# Generated by Django 5.1.4 on 2025-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0005_remove_appointment_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="id_request",
            new_name="appoint_id",
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="ar_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
