# Generated by Django 5.1.4 on 2025-01-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="inquiry_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
